# Generated by Django 4.2.5 on 2023-10-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recapsummary',
            name='recap',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='recap_app.recap'),
        ),
    ]
